"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import {
  Bot,
  CalendarDays,
  ClipboardList,
  Cog,
  Download,
  FileText,
  NotebookPen,
  Search,
  Sparkles,
  User,
  Wrench,
} from "lucide-react"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "@/components/ui/input-group"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"
import { Separator } from "@/components/ui/separator"
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/components/ui/empty"
import {
  reports,
  logbook,
  getEquipment,
  type Report,
  type LogbookEntry,
  type LogCategory,
} from "@/lib/demo-data"
import { cn } from "@/lib/utils"

const reportTypeBadge: Record<Report["type"], string> = {
  "Investigation Report": "bg-destructive/10 text-destructive border-destructive/20",
  "Weekly Summary": "bg-primary/10 text-primary border-primary/20",
  "Monthly Reliability": "bg-success/10 text-success border-success/20",
}

const categoryConfig: Record<
  LogCategory,
  { label: string; icon: typeof Sparkles; badge: string }
> = {
  investigation: {
    label: "Investigation",
    icon: Sparkles,
    badge: "bg-primary/10 text-primary border-primary/20",
  },
  plan: {
    label: "Planning",
    icon: ClipboardList,
    badge: "bg-warning/10 text-warning border-warning/20",
  },
  work: {
    label: "Work",
    icon: Wrench,
    badge: "bg-success/10 text-success border-success/20",
  },
  system: {
    label: "System",
    icon: Cog,
    badge: "bg-muted text-muted-foreground border-border",
  },
  knowledge: {
    label: "Knowledge",
    icon: FileText,
    badge: "bg-primary/10 text-primary border-primary/20",
  },
}

const logFilters = ["All", "Investigation", "Planning", "Work", "System", "Knowledge"] as const

function actorIcon(type: LogbookEntry["actorType"]) {
  if (type === "ai") return Bot
  if (type === "human") return User
  return Cog
}

function downloadReport(report: Report) {
  const text = [
    `${report.title}`,
    `${report.id} · ${report.type} · Generated by ${report.generatedBy} on ${report.date}`,
    "",
    report.summary,
    "",
    ...report.sections.flatMap((s) => [s.heading, s.body, ""]),
  ].join("\n")
  const blob = new Blob([text], { type: "text/plain" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${report.id}.txt`
  a.click()
  URL.revokeObjectURL(url)
}

function ReportsTab() {
  const [selectedId, setSelectedId] = useState<string>(reports[0].id)
  const selected = reports.find((r) => r.id === selectedId) ?? reports[0]

  return (
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.5fr)]">
      <div className="flex flex-col gap-2">
        {reports.map((report) => {
          const active = selected.id === report.id
          return (
            <button
              key={report.id}
              type="button"
              onClick={() => setSelectedId(report.id)}
              className={cn(
                "flex items-start gap-3 rounded-lg border bg-card p-3 text-left transition-colors",
                active ? "border-primary ring-1 ring-primary" : "hover:bg-accent",
              )}
            >
              <div className="flex size-9 shrink-0 items-center justify-center rounded-md bg-muted text-muted-foreground [&_svg]:size-4">
                <FileText />
              </div>
              <div className="flex min-w-0 flex-col gap-1">
                <span className="text-sm font-medium leading-snug text-pretty">
                  {report.title}
                </span>
                <div className="flex flex-wrap items-center gap-2">
                  <Badge variant="outline" className={reportTypeBadge[report.type]}>
                    {report.type}
                  </Badge>
                  <span className="font-mono text-xs text-muted-foreground">
                    {report.id} · {report.date}
                  </span>
                </div>
              </div>
            </button>
          )
        })}
      </div>

      <Card className="h-fit">
        <CardHeader>
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex flex-wrap items-center gap-2">
              <Badge variant="outline" className={reportTypeBadge[selected.type]}>
                {selected.type}
              </Badge>
              <span className="font-mono text-xs text-muted-foreground">
                {selected.id} · {selected.date}
              </span>
              {selected.generatedBy === "AI Agent" && (
                <Badge
                  variant="outline"
                  className="bg-primary/10 text-primary border-primary/20"
                >
                  <Sparkles className="size-3" />
                  AI generated
                </Badge>
              )}
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => downloadReport(selected)}
            >
              <Download />
              Download
            </Button>
          </div>
          <CardTitle className="text-pretty">{selected.title}</CardTitle>
          <CardDescription className="text-pretty">
            {selected.summary}
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-xs font-medium text-muted-foreground">
              Related equipment:
            </span>
            {selected.equipmentIds.map((id) => {
              const eq = getEquipment(id)
              return (
                <Button
                  key={id}
                  render={<Link href={`/equipment/${id}`} />}
                  nativeButton={false}
                  variant="outline"
                  size="sm"
                  className="h-7 font-mono text-xs"
                >
                  {eq?.name ?? id}
                </Button>
              )
            })}
          </div>
          <Separator />
          <div className="flex flex-col gap-3">
            {selected.sections.map((section) => (
              <div key={section.heading} className="rounded-lg border bg-muted/40 p-3">
                <span className="text-sm font-medium">{section.heading}</span>
                <p className="mt-1 text-sm leading-relaxed text-muted-foreground text-pretty">
                  {section.body}
                </p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

function LogbookTab() {
  const [query, setQuery] = useState("")
  const [filter, setFilter] = useState<(typeof logFilters)[number]>("All")

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    return logbook.filter((entry) => {
      if (filter !== "All" && categoryConfig[entry.category].label !== filter)
        return false
      if (!q) return true
      return (
        entry.action.toLowerCase().includes(q) ||
        entry.detail.toLowerCase().includes(q) ||
        entry.actor.toLowerCase().includes(q) ||
        (entry.equipmentId ?? "").toLowerCase().includes(q)
      )
    })
  }, [query, filter])

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <InputGroup className="md:max-w-sm">
          <InputGroupAddon>
            <Search />
          </InputGroupAddon>
          <InputGroupInput
            placeholder="Search logbook entries..."
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            aria-label="Search logbook"
          />
        </InputGroup>
        <ToggleGroup
          variant="outline"
          value={[filter]}
          onValueChange={(v) => {
            const next = v[0]
            if (next) setFilter(next as (typeof logFilters)[number])
          }}
          className="flex-wrap"
        >
          {logFilters.map((f) => (
            <ToggleGroupItem key={f} value={f} className="text-xs">
              {f}
            </ToggleGroupItem>
          ))}
        </ToggleGroup>
      </div>

      {filtered.length === 0 ? (
        <Empty>
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <NotebookPen />
            </EmptyMedia>
            <EmptyTitle>No entries found</EmptyTitle>
            <EmptyDescription>
              No logbook entries match your search. Try a different term or
              clear the category filter.
            </EmptyDescription>
          </EmptyHeader>
        </Empty>
      ) : (
        <div className="relative flex flex-col gap-0">
          {filtered.map((entry, i) => {
            const cat = categoryConfig[entry.category]
            const ActorIcon = actorIcon(entry.actorType)
            const eq = entry.equipmentId ? getEquipment(entry.equipmentId) : null
            return (
              <div key={entry.id} className="flex gap-3">
                <div className="flex flex-col items-center">
                  <div
                    className={cn(
                      "flex size-8 shrink-0 items-center justify-center rounded-full border [&_svg]:size-4",
                      entry.actorType === "ai"
                        ? "border-primary/30 bg-primary/10 text-primary"
                        : entry.actorType === "human"
                          ? "border-success/30 bg-success/10 text-success"
                          : "border-border bg-muted text-muted-foreground",
                    )}
                  >
                    <ActorIcon />
                  </div>
                  {i < filtered.length - 1 && (
                    <div className="w-px flex-1 bg-border" aria-hidden="true" />
                  )}
                </div>
                <div className="flex min-w-0 flex-1 flex-col gap-1 pb-6">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-sm font-medium">{entry.action}</span>
                    <Badge variant="outline" className={cat.badge}>
                      <cat.icon className="size-3" />
                      {cat.label}
                    </Badge>
                  </div>
                  <p className="text-sm leading-relaxed text-muted-foreground text-pretty">
                    {entry.detail}
                  </p>
                  <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
                    <span className="inline-flex items-center gap-1 font-mono text-xs text-muted-foreground">
                      <CalendarDays className="size-3" />
                      {entry.timestamp}
                    </span>
                    <span className="font-mono text-xs text-muted-foreground">
                      {entry.actor}
                    </span>
                    {eq && entry.equipmentId && (
                      <Link
                        href={`/equipment/${entry.equipmentId}`}
                        className="font-mono text-xs text-primary hover:underline"
                      >
                        {eq.name}
                      </Link>
                    )}
                    {entry.refId && (
                      <span className="font-mono text-xs text-muted-foreground">
                        Ref: {entry.refId}
                      </span>
                    )}
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

export function ReportsView() {
  return (
    <Tabs defaultValue="reports" className="flex flex-col gap-4">
      <TabsList className="w-fit">
        <TabsTrigger value="reports">
          <FileText className="size-4" />
          Generated Reports
        </TabsTrigger>
        <TabsTrigger value="logbook">
          <NotebookPen className="size-4" />
          Digital Logbook
        </TabsTrigger>
      </TabsList>
      <TabsContent value="reports">
        <ReportsTab />
      </TabsContent>
      <TabsContent value="logbook">
        <LogbookTab />
      </TabsContent>
    </Tabs>
  )
}
